// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_consultationdialog.cpp"
#include "EWIEGA46WW/moc_diagnosisdialog.cpp"
#include "EWIEGA46WW/moc_doctordialog.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_medicinedialog.cpp"
#include "EWIEGA46WW/moc_patientdialog.cpp"
#include "EWIEGA46WW/moc_searchdialog.cpp"
